### ISSUE TITLE
Keyboard on Exit does not go back to hometimeline

### ISSUE THREAD

**Issue by hassanNS** [TheBenderman/Senior-Design-ALS-Social-Media#46] opened 2017-05-11 17:07 UTC
Navigate to hometimeline.
Select a tweet.
Hit the reply button.
Exit the keyboard.
You will see the screen is empty.

**Comment by KLD0093** [comment] 2017-05-11 17:10
Could you show the code on the OnClick for the 'Replay'. What function gets called when Reply is triggered? I want to see the code for that function.

**Comment by hassanNS** [comment] 2017-05-11 17:18
<img width="578" alt="twwettttprobls" src="https://cloud.githubusercontent.com/assets/2774472/25962600/58907522-364c-11e7-8edb-56fd7f3ad778.png">

**Comment by Pirobi** [comment] 2017-05-11 17:20
You're not hiding the time line game object after clicking reply, right?

**Comment by KLD0093** [comment] 2017-05-11 17:20
I don't see why the issue is Keyboard.

**Comment by hassanNS** [comment] 2017-05-11 17:25
It's not the keyboard. It's the selection manager or the popping mechanism

**Comment by KLD0093** [comment] 2017-05-11 17:26
Could you should the 'Replay' Button in Inspector. I want to see attacked OnClick and Menus.

**Comment by hassanNS** [comment] 2017-05-11 17:31
<img width="940" alt="twiteterereply" src="https://cloud.githubusercontent.com/assets/2774472/25963106/2d61f2a2-364e-11e7-9763-0be886b3d1d4.png">

**Comment by KLD0093** [comment] 2017-05-11 17:33
That's a different function that what we saw above. It should be `replayToTweet` not `TweetFromKeyboard`

**Comment by hassanNS** [comment] 2017-05-11 17:34
Both have the exact same code. I tried swtiching them around to see if it would make a difference

**Comment by hassanNS** [comment] 2017-05-11 17:35
Pressing Exit pops 2 levels and goes back to the multiple tweets selection menu, but nothing shows

**Comment by Pirobi** [comment] 2017-05-11 17:35
So if both have the same code, why are there 2 methods? This is a separate issue but still

**Comment by KLD0093** [comment] 2017-05-11 17:36
Show me the Inspector for the menu showed . I think '`OnResume`' is not bringing back the menu while '`OnPause`' is hiding it.

**Comment by hassanNS** [comment] 2017-05-11 17:39
@Pirobi the arguments are different.

**Comment by hassanNS** [comment] 2017-05-11 17:39
@KLD0093  which menu. The keyboard?

**Comment by KLD0093** [comment] 2017-05-11 17:40
menu. Keyboard it working as intended.

**Comment by hassanNS** [comment] 2017-05-11 17:40
Which menu

**Comment by hassanNS** [comment] 2017-05-11 17:40
I know keyboard is working. I want to know how to setup the menu

**Comment by KLD0093** [comment] 2017-05-11 17:41
> Show me the Inspector for the menu showed

**Comment by hassanNS** [comment] 2017-05-11 17:42
<img width="868" alt="menu" src="https://cloud.githubusercontent.com/assets/2774472/25963539/a25b471a-364f-11e7-9de2-ae2c71cc15b0.png">
 do u mean this

**Comment by KLD0093** [comment] 2017-05-11 17:44
Could you double check if 'OnResume' enables menu?

**Comment by KLD0093** [comment] 2017-05-11 17:49
This is the Selection Manger Logic when it comes to Popping 
![image](https://cloud.githubusercontent.com/assets/4420439/25963765/82bc4066-3650-11e7-8965-5f0d343c5f2e.png)

Pushing 
![image](https://cloud.githubusercontent.com/assets/4420439/25963775/8c79427a-3650-11e7-8cf6-0581c7ac1b14.png)

I don't see how this would break the timeline menu

**Comment by hassanNS** [comment] 2017-05-11 17:50
do I have to put anything on the reply button itself?

**Comment by KLD0093** [comment] 2017-05-11 17:52
> yes it does
No it doesn't. 

If `tweet ` work properly, but `reply `doesn't,  Then there's something wrong with `reply`

**Comment by KLD0093** [comment] 2017-05-11 17:54
In run time, check and see how the menu looks like when it's hidden

**Comment by hassanNS** [comment] 2017-05-11 17:55
it's not something wrong w/ reply. It's that `tweet` is done from the home menu, whereas reply is done from several menus down in the stack.

**Comment by Pirobi** [comment] 2017-05-11 17:57
That shouldn't matter as long as everything is pushed onto and popped off the stack properly

**Comment by hassanNS** [comment] 2017-05-11 17:58
The pop index for the `Exit` button on the keyboard is 4

**Comment by hassanNS** [comment] 2017-05-11 18:00
so when I pause the scene and manually set the Exit button's pop index to `2`, it correctly pops back to the timeline.

**Comment by hassanNS** [comment] 2017-05-11 18:01
how does the pop index get set for the keyboard?

**Comment by KLD0093** [comment] 2017-05-11 18:01
Even if you set that to 10,  Clicking `Exit ` would navigate to main menu. In other words, it should not break.

**Comment by Pirobi** [comment] 2017-05-11 18:03
Which keyboard do you have set? On mine the exit button is pop index 2

**Comment by hassanNS** [comment] 2017-05-11 18:03
again, I want to repeat. It's not "breaking". It's going back to the wrong menu when I hit Exit.

**Comment by hassanNS** [comment] 2017-05-11 18:03
and when I change the pop index to `2`, it goes back to the correct menu

**Comment by hassanNS** [comment] 2017-05-11 18:04
can we do a hangout?

**Comment by Pirobi** [comment] 2017-05-11 18:05
If it shows a blank menu, then something is broken. The pop shouldn't pop the twitter main menu.

**Comment by Pirobi** [comment] 2017-05-11 18:05
But what keyboard do you have set and which exit button are you hitting?

**Comment by hassanNS** [comment] 2017-05-11 18:06
let me put a picture. I didn't set any keyboard beforehand.

**Comment by KLD0093** [comment] 2017-05-11 18:07
isn't it fixed?

**Comment by Pirobi** [comment] 2017-05-11 18:07
I just want to confirm the keyboard used

**Comment by hassanNS** [comment] 2017-05-11 18:10
no. I have to manually set the pop index to 2 by pasuing the scene.

**Comment by hassanNS** [comment] 2017-05-11 18:10
<img width="1247" alt="asdfljasldfkj_exit" src="https://cloud.githubusercontent.com/assets/2774472/25964652/9aca3d7c-3653-11e7-9dad-271827ea8bf8.png">
<img width="1270" alt="keyboard_bug" src="https://cloud.githubusercontent.com/assets/2774472/25964653/9ad00e00-3653-11e7-89db-73bca8ba3dce.png">

1) keyboard
2) exit button

**Comment by Pirobi** [comment] 2017-05-11 18:11
That's the wrong keyboard. That's the phrase keyboard.

**Comment by hassanNS** [comment] 2017-05-11 18:11
how do I set the right one

**Comment by Pirobi** [comment] 2017-05-11 18:12
But, this does mean we have to set that to 2, but the keyboard we will actually be using is correct.
Set the right keyboard in the user settings menu, under UI. I think the code defaulted your user settings to that keyboard before I updated it to default to the new one. Since you had this keyboard set already, it didn't update your default.

**Comment by Pirobi** [comment] 2017-05-11 18:12
Steps:
1)

**Comment by hassanNS** [comment] 2017-05-11 18:16
yeah, though the user settings menu doesn't have an option to set the pop level (not that I think it should)

**Comment by Pirobi** [comment] 2017-05-11 18:16
That's set on the keyboard prefab

**Comment by Pirobi** [comment] 2017-05-11 18:17
I'll make that change.

**Comment by Pirobi** [comment] 2017-05-11 18:26
I think this can be closed once @hassanNS confirms he has the right keyboard and exiting works.

**Comment by KLD0093** [comment] 2017-05-11 18:37
@Pirobi you pushed to Merge Branch 2.0 rather than master.

**Comment by Pirobi** [comment] 2017-05-11 18:42
Never commit directly to master. I was going to make a hot fix branch but  I saw the other commit on merge branch

**Comment by KLD0093** [comment] 2017-05-11 18:44
well, s***. I just committed to master. I'll make branch off master than make future changes there.

**Comment by Pirobi** [comment] 2017-05-11 18:46
Merge Merge-Branch-2.0 to that new branch and then we make our changes from there

**Comment by KLD0093** [comment] 2017-05-11 18:51
Ok. Merged Marge-Branch-2 into Adaptive-Training

**Closed** 2017-05-15 22:23 UTC
Labels: bug
